plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
	id 'net.neoforged.moddev' version '2.0.96'
}

version = '1.3'
group = 'bl4ckscor3.mod.nolancheating'

base {
	archivesName = 'nolancheating-neoforge-1.21.7'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)
println('Java: ' + System.getProperty('java.version') + ' JVM: ' + System.getProperty('java.vm.version') + '(' + System.getProperty('java.vendor') + ') Arch: ' + System.getProperty('os.arch'))

neoForge {
	version = "21.7.23-beta"

	runs {
		client {
			client()
			logLevel = org.slf4j.event.Level.DEBUG
			gameDirectory = project.file("run/client")
			ideName = "NoLANCheating " + ideName.get()
		}
	}

	mods {
		nolancheating {
			sourceSet(sourceSets.main)
		}
	}
}

repositories {
    maven {
        url "https://cursemaven.com/"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
	implementation "curse.maven:mcwifipnp-450250:6671461"
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes(["Specification-Title": "No LAN Cheating",
                    "Specification-Vendor": "bl4ckscor3",
                    "Specification-Version": "${version}",
                    "Implementation-Title": "No LAN Cheating",
                    "Implementation-Version": "${version}",
                    "Implementation-Vendor": "bl4ckscor3"])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
	options.release = 21
}

idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}