# Project
group=bl4ckscor3.mod.nolancheating
version=1.4
minecraft_version=26.2
minecraft_min_version=26.2
java_version=25
license=MIT
mod_id=nolancheating
mod_name=No LAN Cheating
description=Removes the Allow Cheats button from the Open to LAN menu and Create New World screen.
mod_author=bl4ckscor3
source_link=https://github.com/bl4ckscor3/NoLANCheating
cf_link=https://www.curseforge.com/minecraft/mc-mods/no-lan-cheating

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1
mdg_version=2.0.141
fcap_version=26.2.0
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.2.0.6-beta
neoforge_min_version=26.2
neo_mcwifipnp_version=qGvDbtFd

# Fabric
loom_version=1.17-SNAPSHOT
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3
modmenu_version=20.0.0-beta.3
fabric_mcwifipnp_version=5IK13PjO

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
