modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory

[[mods]] #mandatory
	modId="nolancheating" #mandatory
	version="v1.0" #mandatory
	displayName="No LAN Cheating" #mandatory
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="http://minecraft.curseforge.com/projects/no-lan-cheating"
	authors="bl4ckscor3"

[[dependencies.nolancheating]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"