modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/NoLANCheating/blob/1.20.2/LICENSE"

[[mods]]
	modId="nolancheating"
	version="${file.jarVersion}"
	displayName="No LAN Cheating"
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.'''
	issueTrackerURL="http://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/no-lan-cheating"
	authors="bl4ckscor3"

[[mixins]]
    config="nolancheating.mixins.json"

[[dependencies.nolancheating]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"