modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/NoLANCheating/blob/1.17/LICENSE"

[[mods]] #mandatory
	modId="nolancheating" #mandatory
	version="${file.jarVersion}" #mandatory
	displayName="No LAN Cheating" #mandatory
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/no-lan-cheating"
	authors="bl4ckscor3"

[[dependencies.nolancheating]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"