modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/NoLANCheating/blob/1.16/LICENSE"

[[mods]] #mandatory
	modId="nolancheating" #mandatory
	version="v1.0" #mandatory
	displayName="No LAN Cheating" #mandatory
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/no-lan-cheating"
	authors="bl4ckscor3"

[[dependencies.nolancheating]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"