modLoader="javafml"
loaderVersion="[46,)"
license="MIT https://github.com/bl4ckscor3/NoLANCheating/blob/1.20/LICENSE"

[[mods]]
	modId="nolancheating"
	version="${file.jarVersion}"
	displayName="No LAN Cheating"
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.'''
	issueTrackerURL="http://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/no-lan-cheating"
	authors="bl4ckscor3"

[[dependencies.nolancheating]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"