modLoader="javafml"
loaderVersion="[41,)"
license="MIT https://github.com/bl4ckscor3/NoLANCheating/blob/1.19/LICENSE"

[[mods]]
	modId="nolancheating"
	version="${file.jarVersion}"
	displayName="No LAN Cheating"
	description='''Removes the "Allow Cheats" button from the "Open to LAN" menu.'''
	issueTrackerURL="https://github.com/bl4ckscor3/NoLANCheating/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/no-lan-cheating"
	authors="bl4ckscor3"

[[dependencies.nolancheating]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.nolancheating]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"