package bl4ckscor3.mod.nolancheating;

import java.util.Arrays;

import net.minecraft.client.gui.GuiShareToLan;
import net.minecraft.world.biome.Biome;
import net.minecraftforge.client.event.GuiScreenEvent.InitGuiEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;

@Mod(modid=NoLANCheating.MODID, name=NoLANCheating.NAME, version=NoLANCheating.VERSION, acceptedMinecraftVersions="[" + NoLANCheating.MC_VERSION + "]", clientSideOnly=true)
@EventBusSubscriber(modid=NoLANCheating.MODID, value=Side.CLIENT)
public class NoLANCheating
{
	public static final String MODID = "nolancheating";
	public static final String NAME = "No LAN Cheating";
	public static final String VERSION = "v1.2";
	public static final String MC_VERSION = "1.12";
	public Biome previousBiome;
	public int displayTime = 0;
	public int alpha = 0;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Removes the \"Allow Cheats\" button from the \"Open to LAN\" menu.";
		meta.modId = MODID;
		meta.name = NAME;
		meta.version = VERSION;
	}

	@SubscribeEvent
	public static void onGuiInit(InitGuiEvent.Post event)
	{
		if(event.getGui() instanceof GuiShareToLan)
		{
			GuiShareToLan screen = (GuiShareToLan)event.getGui();

			screen.allowCheatsButton.visible = false;
			screen.gameModeButton.x = screen.width / 2 - screen.gameModeButton.width / 2;
		}
	}
}
